############################ MAIN ##############################################
write_log_action:
  path: /write_log_action
  controller: App\Controller\MainController::writeLogAction

############################ STORE #############################################
store_public:
  path: /
  controller: App\Controller\StorePublicController::renderPublicTemplateAction

public_send_message:
  path: /contactus/send
  controller: App\Controller\DashboardInboxController::sendContactUsMessageAction

############################ DASHBOARD #########################################
dashboard_dashboard:
  path: /dashboard
  controller: App\Controller\DashboardDashboardController::renderDashboardDashboardTemplateAction

dashboard_registration:
  path: /dashboard/registration
  controller: App\Controller\DashboardRegistrationController::renderDashboardRegistrationAction
dashboard_register_user_action:
  path: /dashboard/registration/register_user_action
  controller: App\Controller\DashboardRegistrationController::registerUserAction

dashboard_login_user_action:
  path: /dashboard/login_user_action
  controller: App\Controller\MainDashboardController::loginUserAction
dashboard_logout_user_action:
  path: /dashboard/logout_user_action
  controller: App\Controller\MainDashboardController::logoutUserAction

dashboard_profile:
  path: /dashboard/profile
  controller: App\Controller\DashboardProfileController::renderDashboardProfileAction
dashboard_edit_profile_action:
  path: /dashboard/profile/edit_profile_action
  controller: App\Controller\DashboardProfileController::editProfileAction

dashboard_inbox:
  path: /dashboard/inbox
  controller: App\Controller\DashboardInboxController::renderDashboardInboxTemplateAction
dashboard_delete_message_action:
  path: /dashboard/inbox/delete_message_action/{message_id}
  controller: App\Controller\DashboardInboxController::deleteMessageAction

dashboard_orders:
  path: /dashboard/orders
  controller: App\Controller\DashboardOrdersController::renderDashboardOrdersTemplateAction

dashboard_public:
  path: /dashboard/public
  controller: App\Controller\DashboardPublicController::renderDashboardPublicAction
dashboard_get_public_meta_data_action:
  path: /dashboard/public/get_public_meta_data_action
  controller: App\Controller\DashboardPublicController::getPublicMetaDataAction
dashboard_set_public_meta_data_action:
  path: /dashboard/public/set_public_meta_data_action
  controller: App\Controller\DashboardPublicController::setPublicMetaDataAction

dashboard_recommendations:
  path: /dashboard/recommendations
  controller: App\Controller\DashboardRecommendationsController::renderDashboardRecommendationsTemplateAction

dashboard_categories:
  path: /dashboard/categories
  controller: App\Controller\DashboardCategoriesController::renderDashboardCategoriesTemplateAction

dashboard_products:
  path: /dashboard/products
  controller: App\Controller\DashboardProductsController::renderDashboardProductsTemplateAction

dashboard_users:
  path: /dashboard/users
  controller: App\Controller\DashboardUsersController::renderDashboardUsersTemplateAction

dashboard_settings:
  path: /dashboard/settings
  controller: App\Controller\DashboardSettingsController::renderDashboardSettingsTemplateAction

dashboard_languages:
  path: /dashboard/languages
  controller: App\Controller\DashboardLanguagesController::renderDashboardLanguagesTemplateAction

dashboard_analytics:
  path: /dashboard/analytics
  controller: App\Controller\DashboardAnalyticsController::renderDashboardAnalyticsTemplateAction

dashboard_modules:
  path: /dashboard/modules
  controller: App\Controller\DashboardModulesController::renderDashboardModulesTemplateAction

dashboard_logs:
  path: /dashboard/logs
  controller: App\Controller\DashboardLogsController::renderDashboardLogsTemplateAction
dashboard_get_logs_action:
  path: /dashboard/logs/get_logs_action
  controller: App\Controller\DashboardLogsController::getLogsAction
dashboard_delete_log_action:
  path: /dashboard/logs/delete_log_action
  controller: App\Controller\DashboardLogsController::deleteLogAction
dashboard_delete_logs_action:
  path: /dashboard/logs/delete_logs_action
  controller: App\Controller\DashboardLogsController::deleteLogsAction
