############################ MAIN ##############################################
write_log_action:
  path: /write_log_action
  controller: App\Controller\MainController::writeLogAction

############################ STORE #############################################
store_public:
  path: /
  controller: App\Controller\StorePublicController::renderPublicTemplateAction

public_send_message:
  path: /contactus/send
  controller: App\Controller\DashboardInboxController::sendContactUsMessageAction

############################ DASHBOARD #########################################
dashboard_dashboard:
  path: /dashboard
  controller: App\Controller\DashboardDashboardController::renderDashboardDashboardTemplateAction

### REGISTRATION
dashboard_registration:
  path: /dashboard/registration
  controller: App\Controller\DashboardRegistrationController::renderDashboardRegistrationAction
dashboard_register_user_action:
  path: /dashboard/registration/register_user_action
  controller: App\Controller\DashboardRegistrationController::registerUserAction

### LOGIN and LOGOUT
dashboard_login_user_action:
  path: /dashboard/login_user_action
  controller: App\Controller\MainDashboardController::loginUserAction
dashboard_logout_user_action:
  path: /dashboard/logout_user_action
  controller: App\Controller\MainDashboardController::logoutUserAction

### PROFILE
dashboard_profile:
  path: /dashboard/profile
  controller: App\Controller\DashboardProfileController::renderDashboardProfileAction
dashboard_edit_profile_action:
  path: /dashboard/profile/edit_profile_action
  controller: App\Controller\DashboardProfileController::editProfileAction

### INBOX
dashboard_inbox:
  path: /dashboard/inbox
  controller: App\Controller\DashboardInboxController::renderDashboardInboxTemplateAction
dashboard_delete_message_action:
  path: /dashboard/inbox/delete_message_action/{message_id}
  controller: App\Controller\DashboardInboxController::deleteMessageAction

### ORDERS
dashboard_orders:
  path: /dashboard/orders
  controller: App\Controller\DashboardOrdersController::renderDashboardOrdersTemplateAction

### PUBLIC STORE
dashboard_public:
  path: /dashboard/public
  controller: App\Controller\DashboardPublicController::renderDashboardPublicAction

### RECOMMENDATIONS
dashboard_recommendations:
  path: /dashboard/recommendations
  controller: App\Controller\DashboardRecommendationsController::renderDashboardRecommendationsTemplateAction

### CATEGORIES
dashboard_categories:
  path: /dashboard/categories
  controller: App\Controller\DashboardCategoriesController::renderDashboardCategoriesTemplateAction

### PRODUCTS
dashboard_products:
  path: /dashboard/products
  controller: App\Controller\DashboardProductsController::renderDashboardProductsTemplateAction

### USERS
dashboard_users:
  path: /dashboard/settings/users
  controller: App\Controller\DashboardUsersController::renderDashboardUsersTemplateAction
dashboard_get_users_action:
  path: /dashboard/settings/users/get_users_action
  controller: App\Controller\DashboardUsersController::getUsersAction
dashboard_change_user_action:
  path: /dashboard/settings/users/change_user_action
  controller: App\Controller\DashboardUsersController::changeUserAction
dashboard_delete_user_action:
  path: /dashboard/settings/users/delete_user_action
  controller: App\Controller\DashboardUsersController::deleteUserAction

### SETTINGS
dashboard_settings:
  path: /dashboard/settings
  controller: App\Controller\DashboardSettingsController::renderDashboardSettingsTemplateAction
dashboard_get_logs_count_action:
  path: /dashboard/settings/get_logs_count_action
  controller: App\Controller\DashboardSettingsController::getLogsCountAction

### DASHBOARD IMAGES
dashboard_images:
  path: /dashboard/settings/images
  controller: App\Controller\DashboardImagesController::renderDashboardImagesTemplateAction
dashboard_get_images_action:
  path: /dashboard/settings/images/get_images_action
  controller: App\Controller\DashboardImagesController::getImagesAction
dashboard_save_images_action:
  path: /dashboard/settings/images/save_images_action
  controller: App\Controller\DashboardImagesController::saveImagesAction

### DASHBOARD STYLES
dashboard_styles:
  path: /dashboard/settings/styles
  controller: App\Controller\DashboardStylesController::renderDashboardStylesTemplateAction
dashboard_get_styles_action:
  path: /dashboard/settings/styles/get_styles_action
  controller: App\Controller\DashboardStylesController::getStylesAction
dashboard_save_styles_action:
  path: /dashboard/settings/styles/save_styles_action
  controller: App\Controller\DashboardStylesController::saveStylesAction

### DASHBOARD LANGUAGES
dashboard_languages:
  path: /dashboard/settings/languages
  controller: App\Controller\DashboardLanguagesController::renderDashboardLanguagesTemplateAction
dashboard_get_languages_action:
  path: /dashboard/settings/languages/get_languages_action
  controller: App\Controller\DashboardLanguagesController::getLanguagesAction
dashboard_get_language_action:
  path: /dashboard/settings/languages/get_language_action
  controller: App\Controller\DashboardLanguagesController::getLanguageAction
dashboard_add_language_action:
  path: /dashboard/settings/languages/add_language_action
  controller: App\Controller\DashboardLanguagesController::addLanguageAction
dashboard_edit_language_action:
  path: /dashboard/settings/languages/edit_language_action
  controller: App\Controller\DashboardLanguagesController::editLanguageAction
dashboard_delete_language_action:
  path: /dashboard/settings/languages/delete_language_action
  controller: App\Controller\DashboardLanguagesController::deleteLanguageAction
dashboard_save_default_languages_action:
  path: /dashboard/settings/languages/save_default_languages_action_url
  controller: App\Controller\DashboardLanguagesController::saveDefaultLanguagesAction

### DASHBOARD CURRENCIES
dashboard_currencies:
  path: /dashboard/settings/currencies
  controller: App\Controller\DashboardCurrenciesController::renderDashboardCurrenciesTemplateAction
dashboard_get_currencies_action:
  path: /dashboard/settings/currencies/get_currencies_action
  controller: App\Controller\DashboardCurrenciesController::getCurrenciesAction
dashboard_get_currency_action:
  path: /dashboard/settings/currencies/get_currency_action
  controller: App\Controller\DashboardCurrenciesController::getCurrencyAction
dashboard_add_currency_action:
  path: /dashboard/settings/currencies/add_currency_action
  controller: App\Controller\DashboardCurrenciesController::addCurrencyAction
dashboard_edit_currency_action:
  path: /dashboard/settings/currencies/edit_currency_action
  controller: App\Controller\DashboardCurrenciesController::editCurrencyAction
dashboard_delete_currency_action:
  path: /dashboard/settings/currencies/delete_currency_action
  controller: App\Controller\DashboardCurrenciesController::deleteCurrencyAction
dashboard_save_default_currencies_action:
  path: /dashboard/settings/currencies/save_default_currencies_action_url
  controller: App\Controller\DashboardCurrenciesController::saveDefaultCurrenciesAction

### DASHBOARD META
dashboard_meta:
  path: /dashboard/settings/meta
  controller: App\Controller\DashboardMetaController::renderDashboardMetaTemplateAction
dashboard_get_meta_action:
  path: /dashboard/settings/meta/get_meta_action
  controller: App\Controller\DashboardMetaController::getMetaAction
dashboard_save_meta_action:
  path: /dashboard/settings/meta/save_meta_action
  controller: App\Controller\DashboardMetaController::saveMetaAction

### DASHBOARD INFORMATION
dashboard_information:
  path: /dashboard/settings/information
  controller: App\Controller\DashboardInformationController::renderDashboardInformationTemplateAction
dashboard_get_information_action:
  path: /dashboard/settings/information/get_information_action
  controller: App\Controller\DashboardInformationController::getInformationAction
dashboard_save_information_action:
  path: /dashboard/settings/information/save_information_action
  controller: App\Controller\DashboardInformationController::saveInformationAction

### SCRIPTS
dashboard_scripts:
  path: /dashboard/settings/scripts
  controller: App\Controller\DashboardScriptsController::renderDashboardScriptsTemplateAction
dashboard_get_scripts_action:
  path: /dashboard/settings/scripts/get_scripts_action
  controller: App\Controller\DashboardScriptsController::getScriptsAction
dashboard_get_script_action:
  path: /dashboard/settings/scripts/get_script_action
  controller: App\Controller\DashboardScriptsController::getScriptAction
dashboard_add_script_action:
  path: /dashboard/settings/scripts/add_script_action
  controller: App\Controller\DashboardScriptsController::addScriptAction
dashboard_edit_script_action:
  path: /dashboard/settings/scripts/edit_script_action
  controller: App\Controller\DashboardScriptsController::editScriptAction
dashboard_delete_script_action:
  path: /dashboard/settings/scripts/delete_script_action
  controller: App\Controller\DashboardScriptsController::deleteScriptAction

### MODULES
dashboard_modules:
  path: /dashboard/settings/modules
  controller: App\Controller\DashboardModulesController::renderDashboardModulesTemplateAction
dashboard_get_modules_action:
  path: /dashboard/settings/modules/get_modules_action
  controller: App\Controller\DashboardModulesController::getModulesAction
dashboard_get_module_action:
  path: /dashboard/settings/modules/get_module_action
  controller: App\Controller\DashboardModulesController::getModuleAction
dashboard_add_module_action:
  path: /dashboard/settings/modules/add_module_action
  controller: App\Controller\DashboardModulesController::addModuleAction
dashboard_edit_module_action:
  path: /dashboard/settings/modules/edit_module_action
  controller: App\Controller\DashboardModulesController::editModuleAction
dashboard_delete_module_action:
  path: /dashboard/settings/modules/delete_module_action
  controller: App\Controller\DashboardModulesController::deleteModuleAction

### LOGS
dashboard_logs:
  path: /dashboard/settings/logs
  controller: App\Controller\DashboardLogsController::renderDashboardLogsTemplateAction
dashboard_get_logs_action:
  path: /dashboard/settings/logs/get_logs_action
  controller: App\Controller\DashboardLogsController::getLogsAction
dashboard_delete_log_action:
  path: /dashboard/settings/logs/delete_log_action
  controller: App\Controller\DashboardLogsController::deleteLogAction
dashboard_delete_logs_action:
  path: /dashboard/settings/logs/delete_logs_action
  controller: App\Controller\DashboardLogsController::deleteLogsAction
