store_public:
  path: /
  controller: App\Controller\StorePublicController::renderPublicTemplateAction

#write_log_action:
#  path: /write_log_action
#  controller: App\Controller\MainController::writeLogAction

#send_message_action:
#  path: /seand_message_action
#  controller: App\Controller\MainStoreController::sendMessageAction

############################ DASHBOARD #########################################
dashboard_dashboard:
  path: /dashboard
  controller: App\Controller\DashboardDashboardController::renderDashboardDasboardAction

dashboard_registration:
  path: /dashboard/registration
  controller: App\Controller\DashboardRegistrationController::renderDashboardRegistrationAction
