################################# STORE ########################################
store:
  store_language:     1
  pagination_step:    10


################################# DASHBOARD ####################################
dashboard:
  dashboard_language: 1
