App\Entity\CommonSettings:
    type: entity
    table: common_settings
    id:
        settingId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: setting_id
            generator:
                strategy: IDENTITY
    fields:
        settingName:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: setting_name
        settingData:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: setting_data
    lifecycleCallbacks: {  }
