App\Entity\StoreScripts:
    type: entity
    table: store_scripts
    id:
        scriptId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: script_id
            generator:
                strategy: IDENTITY
    fields:
        scriptName:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: script_name
        scriptDescription:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: script_description
        scriptData:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: script_data
    lifecycleCallbacks: {  }
