App\Entity\StoreModules:
    type: entity
    table: store_modules
    id:
        moduleId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: module_id
            generator:
                strategy: IDENTITY
    fields:
        moduleName:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: module_name
        moduleDescription:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: module_description
        moduleData:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: module_data
    lifecycleCallbacks: {  }
